In [56]:
import numpy as np
from itertools import groupby

f = np.arange(50).reshape([10,5])
l =  np.arange(10) + 100
l = l.astype(str)
feats = []
labels = []

for f1, l1 in zip(f,l):
    for _ in range(3):
        feats.append(f1)
        labels.append(l1)
feats = np.array(feats)
labels = np.array(labels)
print(feats)
print(labels)

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [10 11 12 13 14]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [15 16 17 18 19]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [20 21 22 23 24]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [25 26 27 28 29]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [30 31 32 33 34]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [35 36 37 38 39]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [40 41 42 43 44]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [45 46 47 48 49]
 [45 46 47 48 49]]
['100' '100' '100' '101' '101' '101' '102' '102' '102' '103' '103' '103'
 '104' '104' '104' '105' '105' '105' '106' '106' '106' '107' '107' '107'
 '108' '108' '108' '109' '109' '109']


In [57]:
for key, group in groupby(things, lambda x: x[0]):
    listOfThings = " and ".join([thing[1] for thing in group])
    print key + "s:  " + listOfThings + "."

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(key + "s:  " + listOfThings + ".")? (<ipython-input-57-18f622b0f509>, line 3)

In [59]:
for label, group in groupby(zip(labels,feats), lambda x:x[0]):
    grouped_feats = [thing[1] for thing in group]
    grouped_feats = np.array(grouped_feats)
    feat_maxpooled = np.amax(grouped_feats, axis= 0)
    print(type(label))
    print(feat_maxpooled)

<class 'numpy.str_'>
[0 1 2 3 4]
<class 'numpy.str_'>
[5 6 7 8 9]
<class 'numpy.str_'>
[10 11 12 13 14]
<class 'numpy.str_'>
[15 16 17 18 19]
<class 'numpy.str_'>
[20 21 22 23 24]
<class 'numpy.str_'>
[25 26 27 28 29]
<class 'numpy.str_'>
[30 31 32 33 34]
<class 'numpy.str_'>
[35 36 37 38 39]
<class 'numpy.str_'>
[40 41 42 43 44]
<class 'numpy.str_'>
[45 46 47 48 49]


In [60]:
ll = l.astype(str)
ll = ll +"cr"

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [20]:
k = list(feats)

In [21]:
k.extend(k)

In [22]:
k

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49]),
 array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24]),
 array([25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34]),
 array([35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49])]

In [23]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
def __get_map__(path, inv =False):
    
    m = {}
    with open(path, "r") as f:
        text = f.readlines()
    
    for line in text:
        temp = line.strip().split()
        num, activity = int(temp[0]), temp[1]
        if inv:
            m[num] = activity
        else:
            m[activity] = num
    
    return m


In [67]:
p =  r"C:\Users\dcsang\Downloads\mapping.txt"

In [68]:
m1 = __get_map__(p)
m2 = __get_map__(p, True)

In [69]:
m1

{'SIL': 0,
 'pour_cereals': 1,
 'pour_milk': 2,
 'stir_cereals': 3,
 'take_bowl': 4,
 'pour_coffee': 5,
 'take_cup': 6,
 'spoon_sugar': 7,
 'stir_coffee': 8,
 'pour_sugar': 9,
 'pour_oil': 10,
 'crack_egg': 11,
 'add_saltnpepper': 12,
 'fry_egg': 13,
 'take_plate': 14,
 'put_egg2plate': 15,
 'take_eggs': 16,
 'butter_pan': 17,
 'take_knife': 18,
 'cut_orange': 19,
 'squeeze_orange': 20,
 'pour_juice': 21,
 'take_glass': 22,
 'take_squeezer': 23,
 'spoon_powder': 24,
 'stir_milk': 25,
 'spoon_flour': 26,
 'stir_dough': 27,
 'pour_dough2pan': 28,
 'fry_pancake': 29,
 'put_pancake2plate': 30,
 'pour_flour': 31,
 'cut_fruit': 32,
 'put_fruit2bowl': 33,
 'peel_fruit': 34,
 'stir_fruit': 35,
 'cut_bun': 36,
 'smear_butter': 37,
 'take_topping': 38,
 'put_toppingOnTop': 39,
 'put_bunTogether': 40,
 'take_butter': 41,
 'stir_egg': 42,
 'pour_egg2pan': 43,
 'stirfry_egg': 44,
 'add_teabag': 45,
 'pour_water': 46,
 'stir_tea': 47}

In [70]:
m2

{0: 'SIL',
 1: 'pour_cereals',
 2: 'pour_milk',
 3: 'stir_cereals',
 4: 'take_bowl',
 5: 'pour_coffee',
 6: 'take_cup',
 7: 'spoon_sugar',
 8: 'stir_coffee',
 9: 'pour_sugar',
 10: 'pour_oil',
 11: 'crack_egg',
 12: 'add_saltnpepper',
 13: 'fry_egg',
 14: 'take_plate',
 15: 'put_egg2plate',
 16: 'take_eggs',
 17: 'butter_pan',
 18: 'take_knife',
 19: 'cut_orange',
 20: 'squeeze_orange',
 21: 'pour_juice',
 22: 'take_glass',
 23: 'take_squeezer',
 24: 'spoon_powder',
 25: 'stir_milk',
 26: 'spoon_flour',
 27: 'stir_dough',
 28: 'pour_dough2pan',
 29: 'fry_pancake',
 30: 'put_pancake2plate',
 31: 'pour_flour',
 32: 'cut_fruit',
 33: 'put_fruit2bowl',
 34: 'peel_fruit',
 35: 'stir_fruit',
 36: 'cut_bun',
 37: 'smear_butter',
 38: 'take_topping',
 39: 'put_toppingOnTop',
 40: 'put_bunTogether',
 41: 'take_butter',
 42: 'stir_egg',
 43: 'pour_egg2pan',
 44: 'stirfry_egg',
 45: 'add_teabag',
 46: 'pour_water',
 47: 'stir_tea'}

In [132]:
import BreakfastNaive as BF
import importlib
importlib.reload(BF)

<module 'BreakfastNaive' from 'C:\\Users\\dcsang\\PycharmProjects\\feedfwdBF\\BreakfastNaive.py'>

In [134]:
visual_feat_path = r"C:\Users\dcsang\PycharmProjects\embedding\breakfast\bf_kinetics_feat"
text_path = r"C:\Users\dcsang\PycharmProjects\embedding\breakfast\groundTruth"
map_path = r"C:\Users\dcsang\PycharmProjects\embedding\breakfast\mapping.txt"

dataset = BF.BreakfastNaive(visual_feat_path, text_path, map_path)

In [135]:
len(dataset)

11656

In [137]:
dataset[11656]

IndexError: list index out of range

In [140]:
len(dataset.data['vis_feats'])

11656

In [184]:
import torch

In [185]:
train_loader = torch.utils.data.DataLoader(dataset=dataset, 
                                           batch_size=200, 
                                           shuffle=True)

In [187]:
for i, data in enumerate(train_loader):

    print(data["vis_feats"].shape)
    print(data["labels"].shape)
    print(data["labels"].dtype)
    print(data["vis_feats"].requires_grad)
    break

torch.Size([200, 2048])
torch.Size([200])
torch.int32
False


In [149]:
11656/200

58.28

In [ ]:
import os
gt_path = r"C:\Users\dcsang\PycharmProjects\embedding\breakfast\groundTruth"
files = os.listdir(gt_path)
labels = []
for file in files:
    if "coffee" in file:
        print(file)
        with open(os.path.join(gt_path, file), "r") as f:
            temp = f.readlines()
            labels.extend(temp)

In [ ]:
labels

In [122]:
la = set(labels)

In [124]:
la

{'SIL\n',
 'pour_coffee\n',
 'pour_milk\n',
 'pour_sugar\n',
 'spoon_sugar\n',
 'stir_coffee\n',
 'take_cup\n',
 'walk_in\n',
 'walk_out\n'}

In [ ]:
le = set(labels)

In [182]:
outputs.requires_grad

True

In [188]:
import numpy as np

In [193]:
f = r"C:\Users\dcsang\Downloads\Compressed\P03_cam01_P03_cereals"
f2 = r"C:\Users\dcsang\PycharmProjects\embedding\breakfast\bf_kinetics_feat\test\P03_cam01_P03_cereals.npy"

In [194]:
k = np.load(f2)

In [195]:
k.shape

(832, 2048)